In [2]:
import numpy as np
import pandas as pd

In [3]:
df_UNI = pd.read_csv('../data/UNI_NO_LIMPIO.csv')

C:\Users\jacob\AppData\Local\Temp\ipykernel_3960\1387614382.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_UNI = pd.read_csv('../data/UNI_NO_LIMPIO.csv')

In [7]:
df_UNI

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,Season,24,25,26,27
0,1,Eric,Zwayer,RICH,29,19.1,7.2,2.8,5.6,0.503,...,0.5,0.4,0.3,1.0,2.6,2002/2003,NaN,NaN,NaN,NaN
1,2,Stanislav,Zuzak,UCI,29,20.7,7.9,2.9,6.8,0.419,...,1.3,0.4,0.2,1.4,2.1,2002/2003,NaN,NaN,NaN,NaN
2,3,Zeljko,Zupic,UD,32,19.1,6.6,2.3,5.5,0.415,...,0.8,0.4,0.5,1.2,2.3,2002/2003,NaN,NaN,NaN,NaN
3,4,Ezra,Zoschke,OU,6,1.7,0.2,0.0,0.3,0.000,...,0.3,0.0,0.0,0.5,0.2,2002/2003,NaN,NaN,NaN,NaN
4,5,Kirsten,Zoellner,BC,8,1.6,0.4,0.1,0.4,0.333,...,0.0,0.1,0.0,0.1,0.1,2002/2003,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84347,4496,Parker,Braun,MU,20,9.2,2.8,1.0,1.7,0.606,...,0.4,0.1,0.7,0.2,0.6,2020/2021,NaN,NaN,NaN,NaN
84348,4497,Connor,Braun,NU,2,3.0,1.0,0.5,0.5,1.000,...,0.0,0.0,0.0,0.0,0.0,2020/2021,NaN,NaN,NaN,NaN
84349,4498,Christian,Braun,KU,30,31.1,9.7,3.1,8.1,0.380,...,1.9,1.2,0.4,1.3,1.7,2020/2021,NaN,NaN,NaN,NaN
84350,4499,Anthony,Bratton,UTRGV,13,12.6,6.2,2.5,4.0,0.635,...,0.2,0.1,0.5,1.1,1.9,2020/2021,NaN,NaN,NaN,NaN
84351,4500,Robert,Braswell,SU,24,12.1,3.8,1.2,3.3,0.363,...,0.1,0.4,0.3,0.3,1.3,2020/2021,NaN,NaN,NaN,NaN

In [6]:

df_UNI.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84352 entries, 0 to 84351
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       84352 non-null  int64
 1   1       84352 non-null  object
 2   2       84352 non-null  object
 3   3       84352 non-null  object
 4   4       84352 non-null  object
 5   5       84352 non-null  object
 6   6       84352 non-null  object
 7   7       84352 non-null  object
 8   8       84352 non-null  float64
 9   9       84352 non-null  float64
 10  10      84352 non-null  float64
 11  11      84352 non-null  float64
 12  12      84352 non-null  float64
 13  13      84352 non-null  float64
 14  14      84352 non-null  float64
 15  15      84352 non-null  float64
 16  16      84352 non-null  float64
 17  17      84352 non-null  float64
 18  18      84352 non-null  float64
 19  19      84352 non-null  float64
 20  20      84352 non-null  float64
 21  21      84352 non-null  float64
 22  22      84352 non-null  float64
 23  23      84094 non-null  float64
 24  Season  84352 non-null  object
 25  24      4622 non-null   float64
 26  25      2479 non-null   float64
 27  26      59 non-null     float64
 28  27      1 non-null      float64
dtypes: float64(20), int64(1), object(8)
memory usage: 18.7+ MB

In [9]:
df_UNI['Player'] = df_UNI["1"] + ' ' + df_UNI["2"]

In [11]:
df_UNI = df_UNI.drop(["1", "2"], axis=1)

In [12]:
cols = list(df_UNI.columns)
cols = [cols[-1]] + cols[:-1]
df_UNI = df_UNI[cols]

In [13]:
df_UNI.head(2)

,Player,0,3,4,5,6,7,8,9,10,...,19,20,21,22,23,Season,24,25,26,27
0,Eric Zwayer,1,RICH,29,19.1,7.2,2.8,5.6,0.503,0.0,...,0.5,0.4,0.3,1.0,2.6,2002/2003,NaN,NaN,NaN,NaN
1,Stanislav Zuzak,2,UCI,29,20.7,7.9,2.9,6.8,0.419,0.8,...,1.3,0.4,0.2,1.4,2.1,2002/2003,NaN,NaN,NaN,NaN

In [14]:
df_UNI = df_UNI.drop(["24","25","26","27"],axis=1)

In [15]:
df_UNI

,Player,0,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,Season
0,Eric Zwayer,1,RICH,29,19.1,7.2,2.8,5.6,0.503,0.0,...,0.662,1.9,2.6,4.5,0.5,0.4,0.3,1.0,2.6,2002/2003
1,Stanislav Zuzak,2,UCI,29,20.7,7.9,2.9,6.8,0.419,0.8,...,0.667,0.8,2.0,2.7,1.3,0.4,0.2,1.4,2.1,2002/2003
2,Zeljko Zupic,3,UD,32,19.1,6.6,2.3,5.5,0.415,0.7,...,0.691,2.3,3.2,5.4,0.8,0.4,0.5,1.2,2.3,2002/2003
3,Ezra Zoschke,4,OU,6,1.7,0.2,0.0,0.3,0.000,0.0,...,0.500,0.3,0.3,0.7,0.3,0.0,0.0,0.5,0.2,2002/2003
4,Kirsten Zoellner,5,BC,8,1.6,0.4,0.1,0.4,0.333,0.0,...,0.500,0.0,0.3,0.3,0.0,0.1,0.0,0.1,0.1,2002/2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84347,Parker Braun,4496,MU,20,9.2,2.8,1.0,1.7,0.606,0.2,...,0.611,0.5,1.0,1.5,0.4,0.1,0.7,0.2,0.6,2020/2021
84348,Connor Braun,4497,NU,2,3.0,1.0,0.5,0.5,1.000,0.0,...,0.000,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,2020/2021
84349,Christian Braun,4498,KU,30,31.1,9.7,3.1,8.1,0.380,1.7,...,0.786,1.2,4.0,5.2,1.9,1.2,0.4,1.3,1.7,2020/2021
84350,Anthony Bratton,4499,UTRGV,13,12.6,6.2,2.5,4.0,0.635,0.0,...,0.682,1.2,2.0,3.2,0.2,0.1,0.5,1.1,1.9,2020/2021
84351,Robert Braswell,4500,SU,24,12.1,3.8,1.2,3.3,0.363,0.7,...,0.833,0.5,1.4,1.9,0.1,0.4,0.3,0.3,1.3,2020/2021

In [16]:
df_UNI = df_UNI.drop(["0"], axis=1)

In [17]:
new_columns = ["Player", "Team", "GP", "MPG", "PPG", "FGM", "FGA", "FG%", "3PM",
               "3PA", "3P", "FTM", "FTA", "FT%", "ORB", "DRB", "RPG", "APG",
               "SPG", "BPG", "TOV", "PF","Season"]

In [18]:
def rename_columns(df, new_columns):
    """
    Esta función toma un dataframe y una lista de nuevas etiquetas de columna
    y devuelve el dataframe con las nuevas etiquetas de columna aplicadas.
    """
    df = df.rename(columns=dict(zip(df.columns, new_columns)))
    return df

In [19]:
df_UNI = rename_columns(df_UNI, new_columns)

In [20]:
df_UNI

,Player,Team,GP,MPG,PPG,FGM,FGA,FG%,3PM,3PA,...,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF,Season
0,Eric Zwayer,RICH,29,19.1,7.2,2.8,5.6,0.503,0.0,0.0,...,0.662,1.9,2.6,4.5,0.5,0.4,0.3,1.0,2.6,2002/2003
1,Stanislav Zuzak,UCI,29,20.7,7.9,2.9,6.8,0.419,0.8,2.3,...,0.667,0.8,2.0,2.7,1.3,0.4,0.2,1.4,2.1,2002/2003
2,Zeljko Zupic,UD,32,19.1,6.6,2.3,5.5,0.415,0.7,2.3,...,0.691,2.3,3.2,5.4,0.8,0.4,0.5,1.2,2.3,2002/2003
3,Ezra Zoschke,OU,6,1.7,0.2,0.0,0.3,0.000,0.0,0.0,...,0.500,0.3,0.3,0.7,0.3,0.0,0.0,0.5,0.2,2002/2003
4,Kirsten Zoellner,BC,8,1.6,0.4,0.1,0.4,0.333,0.0,0.0,...,0.500,0.0,0.3,0.3,0.0,0.1,0.0,0.1,0.1,2002/2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84347,Parker Braun,MU,20,9.2,2.8,1.0,1.7,0.606,0.2,0.5,...,0.611,0.5,1.0,1.5,0.4,0.1,0.7,0.2,0.6,2020/2021
84348,Connor Braun,NU,2,3.0,1.0,0.5,0.5,1.000,0.0,0.0,...,0.000,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,2020/2021
84349,Christian Braun,KU,30,31.1,9.7,3.1,8.1,0.380,1.7,5.1,...,0.786,1.2,4.0,5.2,1.9,1.2,0.4,1.3,1.7,2020/2021
84350,Anthony Bratton,UTRGV,13,12.6,6.2,2.5,4.0,0.635,0.0,0.0,...,0.682,1.2,2.0,3.2,0.2,0.1,0.5,1.1,1.9,2020/2021
84351,Robert Braswell,SU,24,12.1,3.8,1.2,3.3,0.363,0.7,2.4,...,0.833,0.5,1.4,1.9,0.1,0.4,0.3,0.3,1.3,2020/2021

In [21]:
df_UNI.to_csv('NCAA_LIMPIO.csv', index=False)